---
- name: Create AWS VPC
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create AWS VPC in Singapore Region
    ec2_vpc_net:
      name:             mySGVPC01
      cidr_block:       10.10.0.0/16
      region:           ap-southeast-1
      aws_access_key:   xxxx
      aws_secret_key:   xxxx
      state:            "present"

