---
- name: Allocate a new EIP
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Allocate a new EIP
    ec2_eip:
      state: present
      region:           ap-southeast-1
      aws_access_key:   xxxx
      aws_secret_key:   xxxx
    register: eip

  - name: output the IP
    debug:
      msg: "Allocated IP is {{ eip.public_ip }}"
